[data]
merged_data_path    = "data/raw/hotel_bookings_with_holidays.csv"
processed_data_path = "data/processed/hotel_bookings_processed.csv"
raw_data_path       = "data/raw/hotel_bookings.csv"

[feature]
target = "is_canceled"

[reports]
figures_path    = "reports/figures"
validation_path = "reports/validation_report.txt"
