name: CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master", "dev", "stage"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Install Dependencies
        run: poetry install

      - name: Code Quality - Linting (Flake8)
        run: poetry run flake8 src scripts tests

      - name: Run Unit and Integration Tests with Coverage
        run: poetry run pytest --cov=src --cov-report=xml tests/

      - name: Training Pipeline Smoke Test
        run: poetry run python scripts/train.py --models baseline,logistic
